#!/usr/bin/env python3
"""
Apple Find My Key Generator for Macless-Haystack / OpenHaystack

Generates:
  PREFIX_findmy_key.h   - C header for the ESP32 firmware
  PREFIX_keyfile         - Raw 28-byte advertisement key (binary)
  PREFIX_devices.json    - Import into Haystack Android app
  PREFIX_private.key     - Raw 28-byte private key (binary, keep secret!)

Requirements:
  pip install cryptography

Usage:
  python generate_keys.py [PREFIX] [DEVICE_NAME]
  python generate_keys.py LNF "LNF-MASTER"
"""

import sys
import os
import json
import base64
import hashlib
from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.hazmat.primitives import serialization


def generate_keys(prefix="LNF", name="LNF-MASTER"):
    print(f"\n{'='*56}")
    print(f"  Apple Find My Key Generator")
    print(f"  Prefix: {prefix}  |  Device: {name}")
    print(f"{'='*56}\n")

    # --- Generate EC P-224 key pair ---
    private_key = ec.generate_private_key(ec.SECP224R1())
    priv_numbers = private_key.private_numbers()
    pub_numbers = priv_numbers.public_numbers

    # Private key: 28 bytes (scalar)
    priv_bytes = priv_numbers.private_value.to_bytes(28, byteorder="big")

    # Advertisement key: 28 bytes (x-coordinate of public point)
    adv_key = pub_numbers.x.to_bytes(28, byteorder="big")

    # Derive BLE MAC address (same logic as the ESP32 firmware)
    mac_bytes = bytearray(6)
    mac_bytes[0] = adv_key[0] | 0xC0
    mac_bytes[1:6] = adv_key[1:6]
    mac_str = ":".join(f"{b:02X}" for b in mac_bytes)

    # SHA-256 hash of advertisement key (used by the server to query Apple)
    adv_key_hash = hashlib.sha256(adv_key).hexdigest()

    # --- 1. C header for ESP32 ---
    hex_lines = []
    for i in range(0, 28, 7):
        chunk = adv_key[i : i + 7]
        hex_lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk))
    hex_body = ",\n".join(hex_lines)

    header_path = f"{prefix}_findmy_key.h"
    with open(header_path, "w") as f:
        f.write(
            f"// Auto-generated by generate_keys.py — DO NOT EDIT\n"
            f"// Device: {name}\n"
            f"// BLE MAC: {mac_str}\n"
            f"// Adv key SHA-256: {adv_key_hash[:16]}...\n"
            f"\n"
            f"#ifndef FINDMY_KEY_H\n"
            f"#define FINDMY_KEY_H\n"
            f"\n"
            f"#include <stdint.h>\n"
            f"\n"
            f"static const uint8_t findmy_public_key[28] = {{\n"
            f"{hex_body}\n"
            f"}};\n"
            f"\n"
            f"#endif\n"
        )
    print(f"  [1/4] {header_path:30s}  C header for ESP32")

    # --- 2. Raw binary keyfile ---
    keyfile_path = f"{prefix}_keyfile"
    with open(keyfile_path, "wb") as f:
        f.write(adv_key)
    print(f"  [2/4] {keyfile_path:30s}  Raw 28-byte advertisement key")

    # --- 3. Private key (binary) ---
    privkey_path = f"{prefix}_private.key"
    with open(privkey_path, "wb") as f:
        f.write(priv_bytes)
    print(f"  [3/4] {privkey_path:30s}  Raw 28-byte private key (SECRET)")

    # --- 4. devices.json for Haystack Android app ---
    # Base64-encode keys for JSON
    priv_b64 = base64.b64encode(priv_bytes).decode()
    adv_b64 = base64.b64encode(adv_key).decode()

    # Also export private key in PKCS#8 DER for apps that need it
    priv_der = private_key.private_bytes(
        encoding=serialization.Encoding.DER,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption(),
    )
    priv_der_b64 = base64.b64encode(priv_der).decode()

    device = {
        "id": prefix.lower(),
        "name": name,
        "privateKey": priv_b64,
        "publicKey": adv_b64,
        "symmetricKey": base64.b64encode(os.urandom(32)).decode(),
        "privateKeyPKCS8": priv_der_b64,
        "icon": "suitcase.fill",
        "color": "blue",
        "isDeployed": True,
        "isActive": True,
        "additionalKeys": [],
    }

    devices_path = f"{prefix}_devices.json"
    with open(devices_path, "w") as f:
        json.dump([device], f, indent=2)
    print(f"  [4/4] {devices_path:30s}  Import into Haystack app")

    # --- Summary ---
    print(f"\n{'='*56}")
    print(f"  SUMMARY")
    print(f"{'='*56}")
    print(f"  Advertisement key (base64) : {adv_b64}")
    print(f"  BLE MAC address            : {mac_str}")
    print(f"  Adv key SHA-256            : {adv_key_hash}")
    print(f"{'='*56}")
    print()
    print("  NEXT STEPS:")
    print(f"  1. Copy {header_path} to both:")
    print(f"       tracker_main/findmy_key.h")
    print(f"       checkpoint/findmy_key.h")
    print(f"  2. Copy {devices_path} to backend/data/")
    print(f"  3. Import {devices_path} into the Haystack Android app")
    print(f"  4. Flash the ESP32 firmware via Arduino IDE")
    print(f"  5. Start the backend:  cd backend && docker compose up -d")
    print()
    print("  SECURITY: Keep the private key and devices.json secret!")
    print(f"            Never commit {privkey_path} to git.\n")


if __name__ == "__main__":
    prefix = sys.argv[1] if len(sys.argv) > 1 else "LNF"
    name = sys.argv[2] if len(sys.argv) > 2 else "LNF-MASTER"
    generate_keys(prefix, name)
